site_name: LyonEye
repo_url: https://github.com/DMKM1517/SmartCity
site_author: DMKM1517
pages:
- Home: index.md
- 'Web User Interface': ui.md
- 'Alchemy API': alch.md
- 'Data Pipeline': pipeline.md
theme: readthedocs
